import { ProductType } from "../product-types";

export const Spices: ProductType[] = [
  {
    id: "s1",
    name: "Blackpaper",
    description: "Strong aroma and pure quality spice.",
    category: "Spices",
    frontImage: "/images/products/spices/blackpeper-front.jpg",
    backImage: "/images/products/spices/blackpaper-back.jpg",
  },
  {
    id: "s2",
    name: "Whitepaper",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/whitepeper-front.jpg",
    backImage: "/images/products/spices/whitepaper-back.jpg",
  },
  {
    id: "s3",
    name: "Cinnaman Stick",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/cinnaman-stick-front.jpg",
    backImage: "/images/products/spices/cinnaman-stick-back.jpg",
  },
  {
    id: "s4",
    name: "Cinnaman Powder",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/cinnaman-powder-font.jpg",
    backImage: "/images/products/spices/cinnaman-powder-back.jpg",
  },
  {
    id: "s5",
    name: "Clove Powder",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/clove-powder-front.jpg",
    backImage: "/images/products/spices/clove-powder-back.jpg",
  },
  {
    id: "s6",
    name: "Clove Whole",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/clove-whole-front.jpg",
    backImage: "/images/products/spices/clove-whole-back.jpg",
  },
  {
    id: "s7",
    name: "Nutmeg Powder",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/nutmeg-powder-front.jpg",
    backImage: "/images/products/spices/nutmeg-powder-back.jpg",
  },
  {
    id: "s8",
    name: "Nutmeg Whole",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/nutmeg-whole-front.jpg",
    backImage: "/images/products/spices/nutmeg-whole-back.jpg",
  },
  {
    id: "s9",
    name: "Star Anise",
    description: "Perfect for rich flavor recipes.",
    category: "Spices",
    frontImage: "/images/products/spices/star-anise-front.jpg",
    backImage: "/images/products/spices/star-anise-back.jpg",
  },
];
